# Generated by Django 2.2.6 on 2019-10-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='description',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='type',
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.TextField(max_length=20),
        ),
        migrations.DeleteModel(
            name='MetricType',
        ),
    ]
